global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'hello-world'
    scrape_interval: 5s
    static_configs:
      - targets: ['hello-world:8000']