name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push hello-world image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world:latest ./hello-world
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:latest

      - name: Build and push goodbye-world image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/goodbye-world:latest ./goodbye-world
          docker push ${{ secrets.DOCKER_USERNAME }}/goodbye-world:latest

